import NavBar from "@/components/NavBar";
import "./globals.css";
import { ToastContainer } from "react-toastify";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-slate-100">
        <main className=" ">
          <NavBar/>
          {children}
        </main>
        <ToastContainer
          pauseOnFocusLoss={false}
          pauseOnHover={false}
        />
      </body>
    </html>
  );
}
